In [1]:
import numpy as np
import pandas as pd

In [2]:
def pairwise_matrix(n):
    A = np.ones([n,n])
    for i in range(0,n):
        for j in range(0,n):
            if i<j:
                aij = input('How important is option {} over option {} ?: '.format(i,j))
                A[i,j] = float(aij)
                A[j,i] = 1/float(aij)#Computing the priority vector 
    
    eig_val = np.linalg.eig(A)[0].max()
    eig_vec = np.linalg.eig(A)[1][:,0]
    p = eig_vec/eig_vec.sum()
    return p, eig_val

In [4]:
n = input("Enter the number of Options")
pairwise_matrix(int(n))

Enter the number of Options3
How important is option 0 over option 1 ?: 0.25
How important is option 0 over option 2 ?: 0.5
How important is option 1 over option 2 ?: 0.75


(array([0.15019651+0.j, 0.43324171+0.j, 0.41656178+0.j]),
 (3.1078473338549752+0j))

In [12]:
pr_c = pairwise_matrix(3)[0]  #All Criteria

How important is option 0 over option 1 ?: 0.5
How important is option 0 over option 2 ?: 0.25
How important is option 1 over option 2 ?: 0.75


In [13]:
pr_c

array([0.14741109+0.j, 0.33748714+0.j, 0.51510178+0.j])

In [15]:
pr_c0 = pairwise_matrix(3)[0]  #Option 1

How important is option 0 over option 1 ?: 0.1
How important is option 0 over option 2 ?: 0.2
How important is option 1 over option 2 ?: 0.3


In [16]:
pr_c1 = pairwise_matrix(3)[0]  #Option 2

How important is option 0 over option 1 ?: 0.2
How important is option 0 over option 2 ?: 0.3
How important is option 1 over option 2 ?: 0.6


In [17]:
pr_c2 = pairwise_matrix(3)[0]  #Option 3

How important is option 0 over option 1 ?: 0.3
How important is option 0 over option 2 ?: 0.6
How important is option 1 over option 2 ?: 0.1


In [18]:
pr_c0

array([0.06359845-0.j, 0.3379172 -0.j, 0.59848435-0.j])

In [19]:
pr_c1

array([0.1086005 +0.j, 0.40008766+0.j, 0.49131184+0.j])

In [20]:
pr_c2

array([0.14810339-0.j, 0.18187252-0.j, 0.67002409-0.j])